In [1]:
# import dependencies
import pandas as pd

In [2]:
# Read in Team Table
team_table = pd.read_csv('database_files/team_table.csv', encoding='windows-1252')
team_table

,Franchise,Lg,From,To,Yrs,G,W,L,W/L%,Plyfs,Div,Conf,Champ,Abbreviation
0,ATLANTA HAWKS,NBA,1969,2020,52,4201,2068,2133,0.492,33,5.0,0,0,ATL
1,ST. LOUIS HAWKS,NBA,1956,1968,13,1005,553,452,0.550,12,6.0,0,1,SLH
2,MILWAUKEE HAWKS,NBA,1952,1955,4,281,91,190,0.324,0,0.0,0,0,MLH
3,TRI-CITIES BLACKHAWKS,NBA,1950,1951,2,132,54,78,0.409,1,0.0,0,0,TCB
4,BOSTON CELTICS,NBA/BAA,1947,2020,74,5796,3426,2370,0.591,57,31.0,9,17,BOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,INDIANAPOLIS OLYMPIANS,NBA,1950,1953,4,269,132,137,0.491,4,1.0,0,0,INO
61,SHEBOYGAN RED SKINS,NBA,1950,1950,1,62,22,40,0.355,1,0.0,0,0,SRS
62,ST. LOUIS BOMBERS,NBA/BAA,1947,1950,4,237,122,115,0.515,3,1.0,0,0,SLB
63,WASHINGTON CAPITOLS,NBA/BAA,1947,1951,5,271,157,114,0.579,4,2.0,0,0,WSC
64,WATERLOO HAWKS,NBA,1950,1950,1,62,19,43,0.306,0,0.0,0,0,WAT

In [3]:
# read in NBA awards transition file
nba_results = pd.read_csv('transition_files/nba_awards.csv', encoding='UTF-8')
nba_results

,Season,Lg,Champion,MVP,ROY,PTS,TRB,AST,WS,mvp_player_id,roy_player_id,pts_player_id,trb_player_id,ast_player_id,ws_player_id
0,2019-20,NBA,NaN,G. Antetokounmpo,J. Morant,J. HardenÂ (2335),R. GobertÂ (916),L. JamesÂ (684),J. HardenÂ (13.1),antetgi01,moranja01,hardeja01,goberru01,jamesle01,hardeja01
1,2018-19,NBA,Toronto Raptors,G. Antetokounmpo,L. Doncic,J. HardenÂ (2818),A. DrummondÂ (1232),R. WestbrookÂ (784),J. HardenÂ (15.2),antetgi01,doncilu01,hardeja01,drumman01,westbru01,hardeja01
2,2017-18,NBA,Golden State Warriors,J. Harden,B. Simmons,L. JamesÂ (2251),A. DrummondÂ (1247),R. WestbrookÂ (820),J. HardenÂ (15.4),hardeja01,simmobe01,jamesle01,drumman01,westbru01,hardeja01
3,2016-17,NBA,Golden State Warriors,R. Westbrook,M. Brogdon,R. WestbrookÂ (2558),A. DrummondÂ (1115),J. HardenÂ (907),J. HardenÂ (15.0),westbru01,brogdma01,westbru01,drumman01,hardeja01,hardeja01
4,2015-16,NBA,Cleveland Cavaliers,S. Curry,K. Towns,J. HardenÂ (2376),A. DrummondÂ (1198),R. RondoÂ (839),S. CurryÂ (17.9),curryst01,townska01,hardeja01,drumman01,rondora01,curryst01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,1953-54,NBA,Minneapolis Lakers,NaN,R. Felix,N. JohnstonÂ (1759),H. GallatinÂ (1098),B. CousyÂ (518),N. JohnstonÂ (18.3),NaN,felixra01,johnsne01,gallaha01,cousybo01,johnsne01
67,1952-53,NBA,Minneapolis Lakers,NaN,M. Meineke,N. JohnstonÂ (1564),G. MikanÂ (1007),B. CousyÂ (547),N. JohnstonÂ (15.3),NaN,meinemo01,johnsne01,mikange01,cousybo01,johnsne01
68,1951-52,NBA,Minneapolis Lakers,NaN,"M. Hutchins,Â B. Tosheff",P. ArizinÂ (1674),L. FoustÂ (880),A. PhillipÂ (539),P. ArizinÂ (16.0),NaN,hutchme01,arizipa01,foustla01,phillan01,arizipa01
69,1950-51,NBA,Rochester Royals,NaN,P. Arizin,G. MikanÂ (1932),D. SchayesÂ (1080),A. PhillipÂ (414),G. MikanÂ (23.4),NaN,arizipa01,mikange01,schaydo01,phillan01,mikange01
70,1949-50,NBA,Minneapolis Lakers,NaN,A. Groza,G. MikanÂ (1865),NaN,D. McGuireÂ (386),G. MikanÂ (21.1),NaN,grozaal01,mikange01,NaN,mcguidi01,mikange01

In [4]:
# Setup ID Table
team_ids = pd.DataFrame(team_table['Franchise'])
team_ids['ID'] = team_table['Abbreviation']
team_ids = team_ids.rename(columns={"Franchise": "Champion"})
team_ids

                  Champion   ID
0            ATLANTA HAWKS  ATL
1          ST. LOUIS HAWKS  SLH
2          MILWAUKEE HAWKS  MLH
3    TRI-CITIES BLACKHAWKS  TCB
4           BOSTON CELTICS  BOS
..                     ...  ...
60  INDIANAPOLIS OLYMPIANS  INO
61     SHEBOYGAN RED SKINS  SRS
62       ST. LOUIS BOMBERS  SLB
63     WASHINGTON CAPITOLS  WSC
64          WATERLOO HAWKS  WAT

[65 rows x 2 columns]

In [5]:
# Fill NA
nba_results['Champion'] = nba_results['Champion'].fillna('Playoffs Unfinished')

# Set Champion to Upper
for i in range(71):
    nba_results['Champion'][i] = nba_results['Champion'][i].upper()
nba_results

,Season,Lg,Champion,MVP,ROY,PTS,TRB,AST,WS,mvp_player_id,roy_player_id,pts_player_id,trb_player_id,ast_player_id,ws_player_id
0,2019-20,NBA,PLAYOFFS UNFINISHED,G. Antetokounmpo,J. Morant,J. HardenÂ (2335),R. GobertÂ (916),L. JamesÂ (684),J. HardenÂ (13.1),antetgi01,moranja01,hardeja01,goberru01,jamesle01,hardeja01
1,2018-19,NBA,TORONTO RAPTORS,G. Antetokounmpo,L. Doncic,J. HardenÂ (2818),A. DrummondÂ (1232),R. WestbrookÂ (784),J. HardenÂ (15.2),antetgi01,doncilu01,hardeja01,drumman01,westbru01,hardeja01
2,2017-18,NBA,GOLDEN STATE WARRIORS,J. Harden,B. Simmons,L. JamesÂ (2251),A. DrummondÂ (1247),R. WestbrookÂ (820),J. HardenÂ (15.4),hardeja01,simmobe01,jamesle01,drumman01,westbru01,hardeja01
3,2016-17,NBA,GOLDEN STATE WARRIORS,R. Westbrook,M. Brogdon,R. WestbrookÂ (2558),A. DrummondÂ (1115),J. HardenÂ (907),J. HardenÂ (15.0),westbru01,brogdma01,westbru01,drumman01,hardeja01,hardeja01
4,2015-16,NBA,CLEVELAND CAVALIERS,S. Curry,K. Towns,J. HardenÂ (2376),A. DrummondÂ (1198),R. RondoÂ (839),S. CurryÂ (17.9),curryst01,townska01,hardeja01,drumman01,rondora01,curryst01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,1953-54,NBA,MINNEAPOLIS LAKERS,NaN,R. Felix,N. JohnstonÂ (1759),H. GallatinÂ (1098),B. CousyÂ (518),N. JohnstonÂ (18.3),NaN,felixra01,johnsne01,gallaha01,cousybo01,johnsne01
67,1952-53,NBA,MINNEAPOLIS LAKERS,NaN,M. Meineke,N. JohnstonÂ (1564),G. MikanÂ (1007),B. CousyÂ (547),N. JohnstonÂ (15.3),NaN,meinemo01,johnsne01,mikange01,cousybo01,johnsne01
68,1951-52,NBA,MINNEAPOLIS LAKERS,NaN,"M. Hutchins,Â B. Tosheff",P. ArizinÂ (1674),L. FoustÂ (880),A. PhillipÂ (539),P. ArizinÂ (16.0),NaN,hutchme01,arizipa01,foustla01,phillan01,arizipa01
69,1950-51,NBA,ROCHESTER ROYALS,NaN,P. Arizin,G. MikanÂ (1932),D. SchayesÂ (1080),A. PhillipÂ (414),G. MikanÂ (23.4),NaN,arizipa01,mikange01,schaydo01,phillan01,mikange01
70,1949-50,NBA,MINNEAPOLIS LAKERS,NaN,A. Groza,G. MikanÂ (1865),NaN,D. McGuireÂ (386),G. MikanÂ (21.1),NaN,grozaal01,mikange01,NaN,mcguidi01,mikange01

In [7]:
# Merge Team IDs into NBA Results
nba_results = nba_results.merge(team_ids, on='Champion', how='left')
nba_results

,Season,Lg,Champion,MVP,ROY,PTS,TRB,AST,WS,mvp_player_id,roy_player_id,pts_player_id,trb_player_id,ast_player_id,ws_player_id,ID
0,2019-20,NBA,PLAYOFFS UNFINISHED,G. Antetokounmpo,J. Morant,J. HardenÂ (2335),R. GobertÂ (916),L. JamesÂ (684),J. HardenÂ (13.1),antetgi01,moranja01,hardeja01,goberru01,jamesle01,hardeja01,NaN
1,2018-19,NBA,TORONTO RAPTORS,G. Antetokounmpo,L. Doncic,J. HardenÂ (2818),A. DrummondÂ (1232),R. WestbrookÂ (784),J. HardenÂ (15.2),antetgi01,doncilu01,hardeja01,drumman01,westbru01,hardeja01,TOR
2,2017-18,NBA,GOLDEN STATE WARRIORS,J. Harden,B. Simmons,L. JamesÂ (2251),A. DrummondÂ (1247),R. WestbrookÂ (820),J. HardenÂ (15.4),hardeja01,simmobe01,jamesle01,drumman01,westbru01,hardeja01,GSW
3,2016-17,NBA,GOLDEN STATE WARRIORS,R. Westbrook,M. Brogdon,R. WestbrookÂ (2558),A. DrummondÂ (1115),J. HardenÂ (907),J. HardenÂ (15.0),westbru01,brogdma01,westbru01,drumman01,hardeja01,hardeja01,GSW
4,2015-16,NBA,CLEVELAND CAVALIERS,S. Curry,K. Towns,J. HardenÂ (2376),A. DrummondÂ (1198),R. RondoÂ (839),S. CurryÂ (17.9),curryst01,townska01,hardeja01,drumman01,rondora01,curryst01,CLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,1953-54,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,R. Felix,N. JohnstonÂ (1759),H. GallatinÂ (1098),B. CousyÂ (518),N. JohnstonÂ (18.3),AWARD NOT ISSUED,felixra01,johnsne01,gallaha01,cousybo01,johnsne01,MNL
67,1952-53,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,M. Meineke,N. JohnstonÂ (1564),G. MikanÂ (1007),B. CousyÂ (547),N. JohnstonÂ (15.3),AWARD NOT ISSUED,meinemo01,johnsne01,mikange01,cousybo01,johnsne01,MNL
68,1951-52,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,"M. Hutchins,Â B. Tosheff",P. ArizinÂ (1674),L. FoustÂ (880),A. PhillipÂ (539),P. ArizinÂ (16.0),AWARD NOT ISSUED,hutchme01,arizipa01,foustla01,phillan01,arizipa01,MNL
69,1950-51,NBA,ROCHESTER ROYALS,AWARD NOT ISSUED,P. Arizin,G. MikanÂ (1932),D. SchayesÂ (1080),A. PhillipÂ (414),G. MikanÂ (23.4),AWARD NOT ISSUED,arizipa01,mikange01,schaydo01,phillan01,mikange01,ROR
70,1949-50,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,A. Groza,G. MikanÂ (1865),AWARD NOT ISSUED,D. McGuireÂ (386),G. MikanÂ (21.1),AWARD NOT ISSUED,grozaal01,mikange01,AWARD NOT ISSUED,mcguidi01,mikange01,MNL

In [8]:
# Add Awards Not Issued
nba_results = nba_results.fillna('AWARD NOT ISSUED')
nba_results

,Season,Lg,Champion,MVP,ROY,PTS,TRB,AST,WS,mvp_player_id,roy_player_id,pts_player_id,trb_player_id,ast_player_id,ws_player_id,ID
0,2019-20,NBA,PLAYOFFS UNFINISHED,G. Antetokounmpo,J. Morant,J. HardenÂ (2335),R. GobertÂ (916),L. JamesÂ (684),J. HardenÂ (13.1),antetgi01,moranja01,hardeja01,goberru01,jamesle01,hardeja01,AWARD NOT ISSUED
1,2018-19,NBA,TORONTO RAPTORS,G. Antetokounmpo,L. Doncic,J. HardenÂ (2818),A. DrummondÂ (1232),R. WestbrookÂ (784),J. HardenÂ (15.2),antetgi01,doncilu01,hardeja01,drumman01,westbru01,hardeja01,TOR
2,2017-18,NBA,GOLDEN STATE WARRIORS,J. Harden,B. Simmons,L. JamesÂ (2251),A. DrummondÂ (1247),R. WestbrookÂ (820),J. HardenÂ (15.4),hardeja01,simmobe01,jamesle01,drumman01,westbru01,hardeja01,GSW
3,2016-17,NBA,GOLDEN STATE WARRIORS,R. Westbrook,M. Brogdon,R. WestbrookÂ (2558),A. DrummondÂ (1115),J. HardenÂ (907),J. HardenÂ (15.0),westbru01,brogdma01,westbru01,drumman01,hardeja01,hardeja01,GSW
4,2015-16,NBA,CLEVELAND CAVALIERS,S. Curry,K. Towns,J. HardenÂ (2376),A. DrummondÂ (1198),R. RondoÂ (839),S. CurryÂ (17.9),curryst01,townska01,hardeja01,drumman01,rondora01,curryst01,CLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,1953-54,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,R. Felix,N. JohnstonÂ (1759),H. GallatinÂ (1098),B. CousyÂ (518),N. JohnstonÂ (18.3),AWARD NOT ISSUED,felixra01,johnsne01,gallaha01,cousybo01,johnsne01,MNL
67,1952-53,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,M. Meineke,N. JohnstonÂ (1564),G. MikanÂ (1007),B. CousyÂ (547),N. JohnstonÂ (15.3),AWARD NOT ISSUED,meinemo01,johnsne01,mikange01,cousybo01,johnsne01,MNL
68,1951-52,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,"M. Hutchins,Â B. Tosheff",P. ArizinÂ (1674),L. FoustÂ (880),A. PhillipÂ (539),P. ArizinÂ (16.0),AWARD NOT ISSUED,hutchme01,arizipa01,foustla01,phillan01,arizipa01,MNL
69,1950-51,NBA,ROCHESTER ROYALS,AWARD NOT ISSUED,P. Arizin,G. MikanÂ (1932),D. SchayesÂ (1080),A. PhillipÂ (414),G. MikanÂ (23.4),AWARD NOT ISSUED,arizipa01,mikange01,schaydo01,phillan01,mikange01,ROR
70,1949-50,NBA,MINNEAPOLIS LAKERS,AWARD NOT ISSUED,A. Groza,G. MikanÂ (1865),AWARD NOT ISSUED,D. McGuireÂ (386),G. MikanÂ (21.1),AWARD NOT ISSUED,grozaal01,mikange01,AWARD NOT ISSUED,mcguidi01,mikange01,MNL

In [9]:
# Write the dataframe to a csv
nba_results.to_csv('database_files/nba_awards.csv', index = False, encoding = 'UTF-8')