In [1]:
# import dependencies
import pandas as pd

In [9]:
# read in players data
players_df = pd.read_csv('resources/players_data.csv', encoding='windows-1252')
players_df

,active_from,active_to,birth_date,college,height,name,position,url,weight,NCAA__3ptapg,...,NCAA__3ptpg,NCAA_efgpct,NCAA_fgapg,NCAA_fgpct,NCAA_fgpg,NCAA_ft,NCAA_ftapg,NCAA_ftpg,NCAA_games,NCAA_ppg
0,1991,1995,24-Jun-68,Duke University,06'10'',Alaa Abdelnaby,F-C,/players/a/abdelal01.html,240.0,0.0,...,0.0,NaN,5.6,0.599,3.3,0.728,2.5,1.8,134.0,8.5
1,1969,1978,7-Apr-46,Iowa State University,06'09'',Zaid Abdul-Aziz,C-F,/players/a/abdulza01.html,235.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970,1989,16-Apr-47,"University of California, Los Angeles",07'02'',Kareem Abdul-Jabbar,C,/players/a/abdulka01.html,225.0,NaN,...,NaN,NaN,16.8,0.639,10.7,0.628,7.9,5.0,88.0,26.4
3,1991,2001,9-Mar-69,Louisiana State University,06'01'',Mahmoud Abdul-Rauf,G,/players/a/abdulma02.html,162.0,7.2,...,2.7,NaN,21.9,0.474,10.4,0.863,6.4,5.5,64.0,29.0
4,1998,2003,3-Nov-74,"University of Michigan, San Jose State University",06'06'',Tariq Abdul-Wahad,F,/players/a/abdulta01.html,223.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4571,2018,2018,4-Jan-97,NaN,06'11'',Ante Zizic,F-C,/players/z/zizican01.html,250.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4572,1983,1983,20-Dec-53,Kent State University,07'01'',Jim Zoet,C,/players/z/zoetji01.html,240.0,NaN,...,NaN,NaN,2.9,0.476,1.4,0.429,1.0,0.4,63.0,3.2
4573,1971,1971,7-Jun-48,Duquesne University,06'01'',Bill Zopf,G,/players/z/zopfbi01.html,170.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4574,2017,2018,18-Mar-97,NaN,07'01'',Ivica Zubac,C,/players/z/zubaciv01.html,265.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4575,1949,1949,19-Dec-19,George Washington University,06'03'',Matt Zunic,G-F,/players/z/zunicma01.html,195.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Transform Player Pages into Player Ids
back = '.html'


for i in range(4576):
    try:
        # URL Column
        players_df['url'][i] = players_df['url'].copy()[i][11:]
        players_df['url'][i] = players_df['url'].copy()[i].replace(back, '')
    except (IndexError):
        pass

players_df = players_df.rename(columns={"url": "player_id"})
players_df

C:\Users\clewe\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\clewe\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,active_from,active_to,birth_date,college,height,name,position,player_id,weight,NCAA__3ptapg,...,NCAA__3ptpg,NCAA_efgpct,NCAA_fgapg,NCAA_fgpct,NCAA_fgpg,NCAA_ft,NCAA_ftapg,NCAA_ftpg,NCAA_games,NCAA_ppg
0,1991,1995,24-Jun-68,Duke University,06'10'',Alaa Abdelnaby,F-C,abdelal01,240.0,0.0,...,0.0,NaN,5.6,0.599,3.3,0.728,2.5,1.8,134.0,8.5
1,1969,1978,7-Apr-46,Iowa State University,06'09'',Zaid Abdul-Aziz,C-F,abdulza01,235.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970,1989,16-Apr-47,"University of California, Los Angeles",07'02'',Kareem Abdul-Jabbar,C,abdulka01,225.0,NaN,...,NaN,NaN,16.8,0.639,10.7,0.628,7.9,5.0,88.0,26.4
3,1991,2001,9-Mar-69,Louisiana State University,06'01'',Mahmoud Abdul-Rauf,G,abdulma02,162.0,7.2,...,2.7,NaN,21.9,0.474,10.4,0.863,6.4,5.5,64.0,29.0
4,1998,2003,3-Nov-74,"University of Michigan, San Jose State University",06'06'',Tariq Abdul-Wahad,F,abdulta01,223.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4571,2018,2018,4-Jan-97,NaN,06'11'',Ante Zizic,F-C,zizican01,250.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4572,1983,1983,20-Dec-53,Kent State University,07'01'',Jim Zoet,C,zoetji01,240.0,NaN,...,NaN,NaN,2.9,0.476,1.4,0.429,1.0,0.4,63.0,3.2
4573,1971,1971,7-Jun-48,Duquesne University,06'01'',Bill Zopf,G,zopfbi01,170.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4574,2017,2018,18-Mar-97,NaN,07'01'',Ivica Zubac,C,zubaciv01,265.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4575,1949,1949,19-Dec-19,George Washington University,06'03'',Matt Zunic,G-F,zunicma01,195.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Years Active
players_df['NBA Years Active'] = players_df['active_to'] - players_df['active_from'] + 1
players_df

,active_from,active_to,birth_date,college,height,name,position,player_id,weight,NCAA__3ptapg,...,NCAA_efgpct,NCAA_fgapg,NCAA_fgpct,NCAA_fgpg,NCAA_ft,NCAA_ftapg,NCAA_ftpg,NCAA_games,NCAA_ppg,NBA Years Active
0,1991,1995,24-Jun-68,Duke University,06'10'',Alaa Abdelnaby,F-C,abdelal01,240.0,0.0,...,NaN,5.6,0.599,3.3,0.728,2.5,1.8,134.0,8.5,5
1,1969,1978,7-Apr-46,Iowa State University,06'09'',Zaid Abdul-Aziz,C-F,abdulza01,235.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
2,1970,1989,16-Apr-47,"University of California, Los Angeles",07'02'',Kareem Abdul-Jabbar,C,abdulka01,225.0,NaN,...,NaN,16.8,0.639,10.7,0.628,7.9,5.0,88.0,26.4,20
3,1991,2001,9-Mar-69,Louisiana State University,06'01'',Mahmoud Abdul-Rauf,G,abdulma02,162.0,7.2,...,NaN,21.9,0.474,10.4,0.863,6.4,5.5,64.0,29.0,11
4,1998,2003,3-Nov-74,"University of Michigan, San Jose State University",06'06'',Tariq Abdul-Wahad,F,abdulta01,223.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4571,2018,2018,4-Jan-97,NaN,06'11'',Ante Zizic,F-C,zizican01,250.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4572,1983,1983,20-Dec-53,Kent State University,07'01'',Jim Zoet,C,zoetji01,240.0,NaN,...,NaN,2.9,0.476,1.4,0.429,1.0,0.4,63.0,3.2,1
4573,1971,1971,7-Jun-48,Duquesne University,06'01'',Bill Zopf,G,zopfbi01,170.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4574,2017,2018,18-Mar-97,NaN,07'01'',Ivica Zubac,C,zubaciv01,265.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4575,1949,1949,19-Dec-19,George Washington University,06'03'',Matt Zunic,G-F,zunicma01,195.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [13]:
# Create SchoolIDs

array(['Duke University', 'Iowa State University',
       'University of California, Los Angeles',
       'Louisiana State University',
       'University of Michigan, San Jose State University',
       'University of California', 'Indiana University',
       'Western Kentucky University', 'Salem International University',
       nan, 'Pepperdine University', 'Long Island University',
       'Oral Roberts University', 'Hillsdale College',
       'Baylor University', 'University of Oklahoma',
       'Northwestern University', 'Gardner-Webb University',
       'University of Arizona', 'Boston College',
       'University of Pittsburgh', 'Syracuse University',
       'University of Kentucky', 'Loyola Marymount University',
       'University of Connecticut', 'Michigan State University',
       'DePaul University', 'Missouri State University',
       'Brigham Young University', 'Morehead State University',
       'Washington State University, California State University, Fullerton',
       'Florida State University', 'California State University, Fresno',
       'University of Kansas', 'University of Texas at Austin',
       'University of Kentucky, University of Connecticut',
       'University of Virginia',
       'University of Virginia, California State University, Fresno',
       'University of South Florida', 'West Virginia University',
       'New Mexico State University', 'Marshall University',
       'University of Pennsylvania', 'Temple University',
       'Villanova University',
       'Butler County Community College, Oklahoma State University',
       'University of Miami', 'University of Nevada, Las Vegas',
       'University of Utah, Weber State University', 'Rice University',
       'Duquesne University', 'Liberty University',
       'Vanderbilt University, Pennsylvania State University',
       'Southern Illinois University', 'Wake Forest University',
       'Blinn College', 'Canisius College', 'University of Memphis',
       "Saint Joseph's University", 'Augsburg College',
       'University of Southern California',
       'Ohio State University, University of Kentucky',
       'University of Kentucky, University of Southern California',
       'University of Houston', 'Bradley University',
       'Oklahoma State University', 'Georgia Institute of Technology',
       'University of Missouri', 'Drexel University',
       'University of Illinois at Urbana-Champaign',
       'University of California, Santa Barbara', 'University of Georgia',
       'Creighton University', 'University of Alabama',
       'University of Portland, University of Nevada, Las Vegas',
       'University of Texas at El Paso', 'University of Cincinnati',
       'Niagara University', 'University of Iowa',
       'Fayetteville State University', 'Pennsylvania State University',
       'University of Notre Dame', 'Florida International University',
       'Tulane University', 'Alliance College',
       'Indiana State University',
       'North Carolina Agricultural and Technical State University',
       'Arizona State University', 'Seton Hall University',
       'Santa Clara University',
       'Pennsylvania State University, Iowa State University',
       'University of Nevada, Reno', 'Tennessee Technological University',
       'Fordham University', 'University of Louisville',
       'Eastern Kentucky University', 'Tuskegee University',
       'Rutgers University', 'North Carolina State University',
       'University of New Mexico', 'University of Hawaii',
       'Ohio State University', 'Wichita State University',
       'University of Hartford', 'Vanderbilt University',
       'University of South Carolina',
       'University of North Carolina at Charlotte',
       'University of Oregon',
       "Indiana State University, Saint Augustine's College",
       'California State University, Los Angeles',
       'Northeastern University', 'Auburn University',
       "St. John's University", 'University of North Carolina',
       'Providence College', 'Tennessee State University',
       'University of Akron', 'Washington State University',
       'Kansas State University',
       'West Virginia University Institute of Technology',
       'Oregon State University',
       'University of the Pacific, Georgia Institute of Technology',
       'University of Michigan', 'Kentucky State University',
       'Texas Tech University',
       'Northern Illinois University, University of Illinois at Urbana-Champaign',
       'Ohio University', 'University of Maryland',
       'Albertson College of Idaho, Seattle University',
       'University of Tennessee', 'Old Dominion University',
       'University of Florida', 'Norfolk State University',
       'Southern Methodist University',
       'Midland College, University of North Dakota',
       'Texas A&M University', 'Prairie View A&M University',
       'University of Denver',
       'South Plains College, University of Arkansas',
       'Stanford University', 'University of Minnesota',
       'Drake University',
       'Boston University, Florida International University',
       'Jacksonville University',
       'Georgetown University, Towson University',
       'Winston-Salem State University',
       'University of Wisconsin-Green Bay', 'Oakland University',
       'Marquette University', 'University of Utah',
       'Weber State University',
       'Oregon State University, San Jose State University',
       'California University of Pennslyvania', 'University of Arkansas',
       'Bowling Green State University', 'Valparaiso University',
       'University of Colorado',
       'University of Pittsburgh, University of Nevada, Las Vegas',
       'University of Memphis, University of Kansas',
       'South Dakota State University', 'Monmouth University',
       'University of Wisconsin', 'Dartmouth College',
       'College of the Holy Cross',
       'University of Virginia, University of Texas at Austin',
       'Midland College, University of Oklahoma', 'University of Dayton',
       'University of Arizona, University of Tennessee, Auburn University at Montgomery',
       'University of Bridgeport', 'Georgetown University',
       'Saint Louis University', 'Cheyney University of Pennsylvania',
       'Clemson University', 'Idaho State University',
       'Muhlenberg College',
       'South Carolina State University, University of South Carolina',
       'Western Michigan University',
       'California State University, Fullerton',
       'Grambling State University',
       'Providence College, University of Pennsylvania',
       'University of Detroit Mercy', 'Boston University',
       'Eastern Michigan University', 'University of San Francisco',
       'University of Tulsa', 'Texas Southern University',
       'Princeton University', 'University of Wyoming',
       'Northern Illinois University',
       'University of Kentucky, Villanova University',
       'Xavier University', 'Elon University', 'New York University',
       'Colgate University', 'St. Bonaventure University',
       'University of Charleston', 'University of Toledo',
       'Virginia Polytechnic Institute and State University',
       'Johnson C. Smith University', 'University of Washington',
       'West Virginia Wesleyan College', 'West Texas A&M University',
       'University of Louisiana at Lafayette', 'La Salle University',
       'Texas Christian University, University of California, Irvine',
       'Miami University', 'Humboldt State University',
       'University of Texas at San Antonio',
       'Indian Hills Community College', 'Wayne State University',
       'University of Evansville',
       'University of Oregon, University of Missouri',
       'Okaloosa-Walton Community College', 'Murray State University',
       'George Washington University',
       'Slippery Rock University of Pennsylvania',
       'Louisiana Tech University',
       'University of Houston, New Mexico State University',
       'Mississippi State University, University of Idaho',
       'Mississippi State University', 'McNeese State University',
       'Manhattan College', 'Texas State University',
       'Jackson State University', 'Columbia University',
       'University of Colorado, University of Iowa',
       'Utah State University', 'Iona College', 'Pikeville College',
       'University of Virginia, Vanderbilt University',
       'University of Arizona, Georgia Institute of Technology',
       'San Diego State University',
       'Southern Methodist University, Lamar University',
       'City College of San Francisco', 'Rockhurst University',
       'Indiana University, University of Kansas',
       'University of Rhode Island',
       'University of Massachusetts Amherst',
       'University of Louisville, University of Texas at El Paso',
       'South Carolina State University', 'Purdue University',
       'Northwestern University, University of California',
       'University of Maine, University of Virginia', 'Otterbein College',
       'East Texas State University', 'Guilford College',
       'Vanderbilt University, University of Missouri',
       "Mount St. Mary's University",
       "University of Hawaii, St. John's University",
       'Virginia Military Institute',
       'University of California, Riverside', 'Hardin-Simmons University',
       'University of South Alabama',
       'University of South Alabama, Iowa State University',
       'Gonzaga University', 'University of Montana',
       'Boise State University', 'University of Mississippi',
       'Belmont University',
       'University of Tulsa, University of Missouri',
       'Colorado State University', 'Hofstra University',
       'Ohio Wesleyan University', 'Southeast Missouri State University',
       'Xavier University of Louisiana',
       'Central Connecticut State University',
       'University of Oregon, Eastern Michigan University',
       'Cleveland State University',
       'University of Minnesota, University of Maryland',
       'Houston Baptist University',
       'Indiana University, Georgia Institute of Technology',
       'St. Thomas University', 'Illinois State University',
       'Bloomsburg University of Pennsylvania',
       'University of Rhode Island, University of North Carolina at Charlotte',
       'University of Portland', "Saint Mary's College of California",
       'Howard University, University of Tulsa, University of Colorado',
       'University of New Orleans', 'Georgia State University',
       'Oklahoma State Teachers College',
       'California State University, Long Beach',
       'Mississippi State University, University of Southern Mississippi',
       'Seton Hall University, University of Houston',
       'Villanova University, University of San Francisco',
       'University of South Carolina Upstate',
       'Indiana University, Xavier University', 'University of Maine',
       'Westminster College of Utah', 'Kentucky Wesleyan College',
       'Robert Morris University (PA), University of Detroit Mercy',
       'Georgia Southern University',
       'Liberty University, Duke University', 'Davidson College',
       'Mount San Antonio College', 'Virginia Commonwealth University',
       'San Jose State University', 'Albany State University',
       'Oklahoma Baptist University',
       'University of Kansas, University of Arizona',
       'Delaware State University', 'North Carolina Central University',
       'Howard College, Texas Tech University',
       'Virginia Union University', 'University of North Texas',
       'Midwestern State University', 'Saint Mary of the Plains College',
       'University of Southern California, University of Nevada, Las Vegas, Iowa State University',
       'University of Maryland, University of Arizona',
       'University of Wisconsin-River Falls', 'University of the Pacific',
       "King's College", 'Lawrence Technological University',
       'Seattle University', 'University of Rochester',
       'Clark Atlanta University',
       'University of Washington, Gonzaga University',
       'Tyler Junior College, University of Idaho',
       'Arkansas State University', 'Voorhees College',
       'New Mexico Highlands University', 'Truman State University',
       'University of Oregon, University of Houston',
       'Auburn University, Florida State University',
       'LeMoyne-Owen College', 'Belmont Abbey College',
       'Loyola University of Chicago',
       'Wichita State University, University of Kansas',
       'University of North Carolina, University of California, Los Angeles',
       'University of Montevallo', 'Eastern Illinois University',
       'Yale University', 'Northeastern State University',
       'University of Missouri-Kansas City', 'College of William & Mary',
       'Arkansas State University, University of Mississippi',
       'Wright State University', 'East Carolina University',
       'Kent State University', 'University of Arkansas at Little Rock',
       'Hamline University', 'American International College',
       'Morehouse College', 'University of Kentucky, Syracuse University',
       'University of Minnesota, University of Wyoming',
       'University of California, Irvine', 'Butler University',
       'University of Southern California, University of Nevada, Las Vegas',
       'Wichita State University, University of Texas at Austin',
       'Indiana University, Georgetown University',
       'City College of New York',
       'San Jose State University, University of Nebraska',
       'University of Missouri, University of Detroit Mercy',
       'University of North Carolina at Wilmington',
       'Rutgers University, Manhattan College',
       'University of Maryland Eastern Shore', 'Cornell University',
       'University of Virginia, University of Massachusetts Amherst',
       'Mississippi Valley State University',
       'University of New Mexico, University of California, Santa Barbara',
       'University of Illinois at Chicago', 'Grand Canyon University',
       'University of California, Los Angeles, University of Texas at El Paso',
       'Saint Francis University',
       'University of California, California State University, Fresno',
       'Brooklyn College', 'Bethune-Cookman College',
       'Indiana University, Ohio State University',
       'Fairfield University',
       'University of California, Los Angeles, Loyola Marymount University',
       'Elizabeth City State University', 'DePauw University',
       'Austin Peay State University, Oral Roberts University',
       'University of Michigan, Boston College',
       'Sam Houston State University',
       'Duke University, Syracuse University',
       'Auburn University, Georgia Institute of Technology',
       'Western Carolina University',
       'University of Kansas, University of New Mexico',
       'McNeese State University, Northwestern State University',
       'Montana State University',
       'Gardner-Webb University, Jacksonville University',
       'Fort Valley State University', 'Alabama A&M University',
       'Delta State University, University of Mississippi',
       'University of California, Los Angeles, University of New Mexico',
       'College of Charleston', 'Gannon University',
       'University of Central Florida, Oklahoma State University',
       'West Texas A&M University, Auburn University at Montgomery',
       'University of Florida, University of South Florida',
       'University of California, Irvine, University of New Orleans',
       'Bradley University, University of New Mexico',
       'Trenton State University',
       'Clemson University, University of Oklahoma',
       'Boston College, University of Wisconsin',
       'University of Tennessee, University of California',
       'Oklahoma City University', 'Harvard University',
       'Hampton University', 'University of Texas-Pan American',
       'North Carolina State University, Iona College',
       'Southern University and A&M College',
       'University of Florida, University of Louisiana at Lafayette',
       'California Western Uiversity', 'Brown University',
       'Seattle University, California State University, Long Beach',
       'University of Minnesota Duluth',
       'University of Illinois at Urbana-Champaign, University of Evansville',
       'Franklin College',
       'Iowa State University, Louisiana State University',
       'Mississippi State University, University of Notre Dame',
       'Utah Valley State College, Brigham Young University',
       'University of Richmond', 'North Park University',
       'North Carolina State University, Auburn University',
       'Wingate University',
       'Lamar University, University of New Orleans',
       'Southern Illinois University, University of Georgia, Pfeiffer University',
       'Austin Peay State University',
       'Western Carolina University, University of Georgia',
       'Acadia University',
       'Oklahoma City University, University of Kansas',
       'University of Arkansas at Pine Bluff', 'Mount Union College',
       'Boston College, California State University, Fresno',
       'Jacksonville University, University of Houston',
       'Ashland University', 'University of Northern Colorado',
       'Indiana University-Purdue University Indianapolis',
       'Queens College',
       'California State University, Fresno, San Diego State University',
       'Mississippi State University, Duke University',
       'University of Nebraska',
       'Auburn University, University of South Carolina',
       'Springfield College', 'University of Tennessee at Martin',
       'University of Missouri, Southern Illinois University',
       'Central Michigan University', 'Thomas More College',
       'University of Oklahoma, University of Notre Dame',
       'Alcorn State University, Jackson State University',
       'Eastern New Mexico University',
       'University of Arkansas, University of Missouri',
       'Pennsylvania State University, Saint Francis University',
       'Wilberforce University',
       "St. John's University, Cleveland State University",
       'Virginia Commonwealth University, Temple University',
       'University of North Dakota',
       'University of Alabama at Birmingham',
       'Butler County Community College',
       "South Plains College, St. Mary's University",
       'Florida Agricultural and Mechanical University',
       'Lamar University', 'Midland College',
       'Washington & Jefferson College',
       'University of Wisconsin-Parkside',
       'University of Arkansas, California State University, Fresno',
       'University of Illinois at Chicago, Robert Morris University (IL)',
       'William Paterson University', 'East Tennessee State University',
       'Bemidji State University',
       'Cameron University, Southern University and A&M College',
       'Baylor University, University of Nebraska',
       'Stephen F. Austin State University', 'Dillard University',
       'University of Idaho',
       'University of Southern California, Michigan State University',
       'University of Montana, East Texas State University',
       'Aurora University',
       'Loyola Marymount University, University of California, Santa Barbara',
       'Huntington University',
       'Louisiana State University, San Diego State University',
       'Iowa State University, Syracuse University',
       'University of Tampa',
       'Georgetown University, University of Nevada, Las Vegas',
       'Rutgers University, Long Island University',
       'Rutgers University, Duke University',
       'Northeast Mississippi Community College, Mississippi State University',
       'University of the District of Columbia',
       'State University of New York College at Buffalo, Vanderbilt University',
       'Assumption College',
       'University of Minnesota, University of Central Florida',
       'Wichita State University, California State University, Fullerton',